### ISSUE TITLE
brawlup.js - v2

### ISSUE THREAD

**Issue by alputv** [brawlup/brawlup.js#6]
Send ideas or codes for ~~potential~~ `v2` update for **brawlup.js**!

**Comment by apoorvcodes** [comment]
I would suggest to use TypeScript

**Comment by alputv** [comment]
I don't know TypeScript... But I added [typings](https://github.com/brawlup/brawlup.js/blob/dev/typings/index.d.ts) (with typescript)!

**Comment by alputv** [comment]
See #8
